name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.1'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
    - name: Run the test suite
      run: bundle exec rspec spec/

    - name: Build and publish gem to Github Packages
      uses: jstastny/publish-gem-to-github@master
      # setting this to re-release previous versions
      continue-on-error: true
      with:
        token: ${{ secrets.GH_TOKEN }}
        owner: ilovemysillybanana

    - name: publish gem
      run: |
        mkdir -p $HOME/.gem
        touch $HOME/.gem/credentials
        chmod 0600 $HOME/.gem/credentials
        printf -- "---\n:rubygems_api_key: ${GEM_HOST_API_KEY}\n" > $HOME/.gem/credentials
        gem build *.gemspec
        gem push *.gem
      env:
        GEM_HOST_API_KEY: "${{secrets.RUBY_GEMS}}"

    # - name: Release Gem on RubyGems
    #   # if: contains(github.ref, 'refs/tags/v')
    #   uses: cadwallion/publish-rubygems-action@master
    #   env:
    #     GITHUB_TOKEN: ${{secrets.GH_TOKEN}}
    #     RUBYGEMS_API_KEY: ${{secrets.RUBY_GEMS}}
    #     RELEASE_COMMAND: |-
    #       gem build j_sdk &&
    #       gem push j_sdk-0.1.0.gem -k ${{secrets.RUBY_GEMS}}