name: Ruby

on:
  push:
    branches:
      - master

  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby:
          - '3.1.1'

    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - name: Run the default task
      run: bundle exec rake
    - name: Run the test suite
      run: bundle exec rspec spec/

    - name: Build and publish gem to Github Packages
      uses: jstastny/publish-gem-to-github@master
      # setting this to re-release previous versions
      continue-on-error: true
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        owner: ilovemysillybanana